import type { Rule } from "./load-rules.js";

export function renderAgentsMd(rules: Rule[]): string {
  const grouped = groupByCategory(rules);

  const lines: string[] = [];

  lines.push("# AGENTS.md");
  lines.push("");
  lines.push("This file is generated by RuleDev Kit.");
  lines.push("Follow these rules when modifying this repository.");
  lines.push("");

  for (const [category, categoryRules] of Object.entries(grouped)) {
    lines.push(`## ${category}`);
    lines.push("");

    for (const rule of categoryRules) {
      lines.push(`### ${rule.title}`);
      lines.push("");
      lines.push(`- Rule ID: \`${rule.id}\``);
      lines.push(`- Severity: \`${rule.severity}\``);
      lines.push("");
      lines.push(rule.instruction.trim());
      lines.push("");
    }
  }

  return `${lines.join("\n")}\n`;
}

function groupByCategory(rules: Rule[]): Record<string, Rule[]> {
  return rules.reduce<Record<string, Rule[]>>((acc, rule) => {
    acc[rule.category] ??= [];
    acc[rule.category].push(rule);
    return acc;
  }, {});
}
